#lang racket

(require css-expr)

(define main-purple  '|#a0a|)
(define half-purple  '|#808|)
(define dark-purple  '|#480048|)
(define light-purple '|#c0c|)

(define black '|#222|)
(define gray  '|#666|)
(define white '|#ccc|)
;(define white '|rgba(255,255,255,0.5)|)

(define main-green  '|#0a0|)
(define half-green  '|#080|)
(define light-green '|#0c0|)
(define dark-green  '|#004800|)

(define style
  `(
    [* #:box-sizing 'border-box]
    [body
     #:margin (40px auto)
     #:max-width 650px
     #:lineheight 1
     #:font-size 18px
     #:color ,main-purple
     #:background-color ,black
     #:padding (0 10px)
     #:font-family |Calibri, Verdana, sans-serif|]
    
    [header .resume-item footer .resume-accordion
     #:background-color ,dark-purple
     #:border-radius 20px
     #:padding (15px 15px 15px 5px)
     #:margin (15px 0 15px 0)]

    [a
     #:color ,main-green
     #:text-decoration none]
    [a:visited
     #:color ,half-green]
    [a:hover
     #:color ,light-green
     #:text-decoration none]
    [.nav-item
     #:margin-right 10px]

    [.accordion
     #:background-color ,dark-green
     #:color ,main-green]
    [.accordion:hover
     #:background-color ,half-green]
    [.accordion.active
     #:background-color ,dark-purple
     #:color ,main-purple]
    [.accordion.active:hover
     #:background-color ,half-purple]
    [.accordion:after
     #:content "+"
     #:float right]
    [.accordion.active:after
     #:content "-"
     #:float right]
    [.accordion-panel
     #:overflow hidden
     #:transition (0.4s ease-in-out)
     #:opacity 0
     #:max-height 0]
    [.accordion-panel.show
     #:opacity 1
     #:max-height none]
    ))
  
(define css
 (string->bytes/utf-8
  (css-expr->css
   (css-expr ,@style))))

(define file (open-output-file "../stylesheets/main.css" #:exists 'replace))
(write-bytes css file)
(close-output-port file)


;/* CSS - Cascading Style Sheet */
;/* Palette color codes */
;/* Palette URL: http://paletton.com/#uid=34W0u0kw0qgm4xjspvjAMlsIUgd */
;
;/* Feel free to copy&paste color codes to your application */
;
;
;/* As hex codes */
;
;.color-primary-0 { color: #880088 }	/* Main Primary color */
;.color-primary-1 { color: #A935A9 }
;.color-primary-2 { color: #A212A2 }
;.color-primary-3 { color: #6F006F }
;.color-primary-4 { color: #540054 }
;
;.color-secondary-1-0 { color: #54BA00 }	/* Main Secondary color (1) */
;.color-secondary-1-1 { color: #8EE447 }
;.color-secondary-1-2 { color: #72DE19 }
;.color-secondary-1-3 { color: #459800 }
;.color-secondary-1-4 { color: #347300 }
;
;.color-secondary-2-0 { color: #D1BE00 }	/* Main Secondary color (2) */
;.color-secondary-2-1 { color: #FFEF4F }
;.color-secondary-2-2 { color: #FAE51C }
;.color-secondary-2-3 { color: #AB9B00 }
;.color-secondary-2-4 { color: #817500 }
;
;
;
;/* As RGBa codes */
;
;.rgba-primary-0 { color: rgba(136,  0,136,1) }	/* Main Primary color */
;.rgba-primary-1 { color: rgba(169, 53,169,1) }
;.rgba-primary-2 { color: rgba(162, 18,162,1) }
;.rgba-primary-3 { color: rgba(111,  0,111,1) }
;.rgba-primary-4 { color: rgba( 84,  0, 84,1) }
;
;.rgba-secondary-1-0 { color: rgba( 84,186,  0,1) }	/* Main Secondary color (1) */
;.rgba-secondary-1-1 { color: rgba(142,228, 71,1) }
;.rgba-secondary-1-2 { color: rgba(114,222, 25,1) }
;.rgba-secondary-1-3 { color: rgba( 69,152,  0,1) }
;.rgba-secondary-1-4 { color: rgba( 52,115,  0,1) }
;
;.rgba-secondary-2-0 { color: rgba(209,190,  0,1) }	/* Main Secondary color (2) */
;.rgba-secondary-2-1 { color: rgba(255,239, 79,1) }
;.rgba-secondary-2-2 { color: rgba(250,229, 28,1) }
;.rgba-secondary-2-3 { color: rgba(171,155,  0,1) }
;.rgba-secondary-2-4 { color: rgba(129,117,  0,1) }
;
;
;
;/* Generated by Paletton.com © 2002-2014 */
;/* http://paletton.com */
